# Generated by Django 4.2.3 on 2023-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('xstate_json', models.JSONField()),
                ('generated_parser', models.TextField()),
                ('journal', models.TextField()),
                ('build_uuid', models.UUIDField()),
                ('check_uuid', models.UUIDField()),
            ],
        ),
    ]
