name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/data-plumber

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/data-plumber-github-actions-role
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    - name: Build images
      run: |
        docker compose build
        docker tag data-plumber-backend:latest $ECR_REPOSITORY/data-plumber-backend:latest
        docker tag data-plumber-nginx:latest $ECR_REPOSITORY/data-plumber-nginx:latest

    - name: Push images
      run: |
        docker push $ECR_REPOSITORY/data-plumber-backend:latest
        docker push $ECR_REPOSITORY/data-plumber-nginx:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster data-plumber-cluster --service data-plumber-service --force-new-deployment
